spring:
  application:
    name: YuQing-FastDFS
server:
  port: 8088
  context-path: /fdfs


fdfs:
  so-timeout: 1501
  connect-timeout: 601 
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  web-server-url: 192.168.92.92/
  tracker-list: 192.168.92.92:22122